### ISSUE TITLE
Error with manual subscription

### ISSUE THREAD

**Issue by mquandalle** [kadirahq/fast-render#146]
Hi @arunoda,

Fast-render produces some errors if the publication uses the DDP low level API, ie `this.ready()`. Here is a code example:

```js
Meteor.publish('test', function() {
  this.ready();
});

FastRender.onAllRoutes(function() {
  this.subscribe('test');
});
```

This produces the following in the console:

```
W20151030-00:26:22.562(1)? (STDERR) Publish handler for null sent no ready signal
W20151030-00:26:25.288(1)? (STDERR) Publish handler for null sent no ready signal
```

If there were some data on the publication it would be correctly transmitted by fast-render, the issue is only the error in the logs.

**Comment by mquandalle** [comment]
Hum it seems something more subtle is going on...

Here is a clonable reproduction in case anyone care: https://github.com/wekan/wekan/tree/fast-render

**Comment by arunoda** [comment]
Just by looking at this, it seems like a issue with a null publication. I
will try to reproduce.

**Comment by mquandalle** [comment]
This is probably a side effect of a third-party package, `3stack:presence` as I was able to demonstrate in this minimal clonable reproduction: https://github.com/mquandalle/meteor-fast-render-issue-146

**Comment by mquandalle** [comment]
Ok actually that was easy, this package has a `null` publication, https://github.com/3stack-software/meteor-presence/blob/c8b2ea9ffccdb12a3abd05ec87bbb3546918aa9c/lib/server/presence.coffee#L26. Sorry for the false alarm.

**Comment by arunoda** [comment]
No problem.
