### ISSUE TITLE
How to populate 'null' collection

### ISSUE THREAD

**Issue by avalanche1** [kadirahq/fast-render#148]
How can I manually populate local `collection = new Mongo.Collection(null)` with FR-injected data?

**Comment by arunoda** [comment]
You can't do that. Local collection do not have any connection with the server. You need to manually populate it.

**Comment by avalanche1** [comment]
If I do
```coffee
Meteor.publish 'posts', -> Posts.find()
FastRender.route '/addPost', -> this.subscribe('posts')`
```
the Posts collection gets populated automatically.
So why I can not populate another collection?
