### ISSUE TITLE
SEO: static text not included in text/inject-data

### ISSUE THREAD

**Issue by steinitz** [kadirahq/fast-render#152]
Hi,

Thank you for sharing fast-render.

I want to make sure I'm understanding fast-render with respect to google crawling of static text.

Viewing page source shows that fast-render works well making text from the database appear in the text/inject-data script block for Google to see.  

However, our site contains some pages which contain only static text (not from the database).  Viewing page source indicates that fast-render does not make that static text appear for google's benefit and that, not surprisingly, the static text is nowhere to be seen at all in the page source (and so, I think, invisible to Google).  

Writing this, I'm realizing that perhaps static text is not included in the html which fast-render loads as part of its process, or, at least, static text has no destination in the fast-rendered page source.

In any case, I'd appreciate any clarifications on fast-render and static text.

Cheers

**Comment by arunoda** [comment]
Hi, fast-render is not directly related to SEO and Google doesn't understand FastRender data. 

Here's what it does. It will simply fetch data related to the initial load along with the HTML. So the client side app doesn't need until the DDP connection is made.
