### ISSUE TITLE
error on fast-rendering path: (...) ; error: TypeError: dynamics.slice is not a function

### ISSUE THREAD

**Issue by tomyo** [kadirahq/fast-render#192]
Hi, I started getting this error:

at Object.Meteor.bindEnvironment (packages/meteor.js:1166:41)
at PublishContext._.extend.onStop (packages/ddp-server/livedata_server.js:1226:23)
at Context.processPublication (packages/flean_fast-render.js:497:18)
at packages/flean_fast-render.js:313:15
at Array.forEach (native)
at Context.<anonymous> (packages/flean_fast-render.js:310:18)
at packages/flean_fast-render.js:285:18
at Array.forEach (native)
at packages/flean_fast-render.js:284:31

It happens when it renders any route.

I commented this line I had in /lib/router.coffee, nothing changed:
```
FastRender.onAllRoutes (path) ->
  this.subscribe 'user'
```
I'm using Meteor 1.5.1, all packages updated

Any idea someone?

**Comment by tomyo** [comment]
Is gone after reverting last packages update commit, the guilty is here somewhere:

```
-aldeed:tabular@1.6.1
+aldeed:tabular@1.2.0
-dburles:collection-helpers@1.1.0
+dburles:collection-helpers@1.0.4
-fourseven:scss@3.13.0
+fourseven:scss@3.4.3
-lepozepo:s3@5.2.5
+lepozepo:s3@5.1.10
-meteor@1.7.1
+meteor@1.7.0
-meteorspark:util@0.2.0
-momentjs:moment@2.18.1
-mongo@1.1.22
+momentjs:moment@2.14.4
+mongo@1.1.19
-nicolaslopezj:router-layer@0.1.0
+nicolaslopezj:router-layer@0.0.11
-npm-mongo@2.2.30
+npm-mongo@2.2.24
-summernote:standalone@0.8.1
-tap:i18n@1.8.2
+summernote:standalone@0.6.16
+tap:i18n@1.4.1
-useraccounts:bootstrap@1.14.2
+useraccounts:bootstrap@1.12.4
```

**Comment by tomyo** [comment]
meteor@1.7.0 -> meteor@1.7.1  it is.

**Comment by derwaldgeist** [comment]
Same here after upgrading from Meteor 1.5 to Meteor 1.6 (meteor@1.8.1). Did you ever solve this?

**Comment by derwaldgeist** [comment]
Just found this: https://github.com/meteor/meteor/issues/9003
